# PyCity Schools Analysis

* As a whole, schools with higher budgets, did not yield better test results. By contrast, schools with higher spending per student actually (\$645-675) underperformed compared to schools with smaller budgets (<\$585 per student).

* As a whole, smaller and medium sized schools dramatically out-performed large sized schools on passing math performances (89-91% passing vs 67%).

* As a whole, charter schools out-performed the public district schools across all metrics. However, more analysis will be required to glean if the effect is due to school practices or the fact that charter schools tend to serve smaller student populations per school. 
---

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas Data Frames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

## District Summary

* Calculate the total number of schools

* Calculate the total number of students

* Calculate the total budget

* Calculate the average math score 

* Calculate the average reading score

* Calculate the overall passing rate (overall average score), i.e. (avg. math score + avg. reading score)/2

* Calculate the percentage of students with a passing math score (70 or greater)

* Calculate the percentage of students with a passing reading score (70 or greater)

* Create a dataframe to hold the above results

* Optional: give the displayed data cleaner formatting

In [2]:
numschools = school_data["school_name"].count()

numstudents = student_data["student_name"].count()

totalbudget = school_data["budget"].sum()

mathavg = student_data["math_score"].mean()

readavg = student_data["reading_score"].mean()

In [3]:
#Percentage of students with a passing math score
passmath = student_data.loc[(student_data["math_score"]) >= 70]
passmathcount = passmath["math_score"].count()
percpassmath = (passmathcount/numstudents) * 100
percpassmath

74.9808526933878

In [4]:
#Percentage of students with a passing reading score
passread = student_data.loc[(student_data["reading_score"]) >= 70]
passreadcount = passread["reading_score"].count()
percpassreading = (passreadcount/numstudents) * 100
percpassreading

85.80546336482001

In [5]:
#Overall passing rate
overallpass = (percpassmath + percpassreading)/2
overallpass

80.39315802910392

In [6]:
#Dataframe to hold results
summary = {
    "Total Schools": numschools,
    "Total Students" : numstudents,
    "Total Budget" : totalbudget,
    "Math Score Average" : mathavg,
    "Reading Score Average" : readavg,
    "Passing Math Percent" : percpassmath,
    "Passing Reading Percent" : percpassreading,
    "Overall Passing Percent" : overallpass  
}

summary_df = pd.DataFrame([summary])
summary_df = summary_df[["Total Schools",
                   "Total Students","Total Budget","Math Score Average", "Reading Score Average",
                   "Passing Math Percent", "Passing Reading Percent", "Overall Passing Percent" ]]

summary_df

,Total Schools,Total Students,Total Budget,Math Score Average,Reading Score Average,Passing Math Percent,Passing Reading Percent,Overall Passing Percent
0,15,39170,24649428,78.985371,81.87784,74.980853,85.805463,80.393158

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)
  
* Create a dataframe to hold the above results

## Top Performing Schools (By Passing Rate)

* Sort and display the top five schools in overall passing rate

In [8]:
school_data["per Student Budget"] = school_data["budget"]/school_data["size"]
avgmathreadscore = student_data.groupby(["school_name"])["math_score", "reading_score"].mean().reset_index()
school_data = school_data.merge(avgmathreadscore, how= "outer", on="school_name")

In [9]:
passreadsum = student_data[student_data["reading_score"]>=70]
passmathsum = student_data[student_data["math_score"]>=70]
passread_count = passreadsum.groupby(["school_name"])["reading_score"].count().reset_index()

In [10]:
passcounter = passmathsum.merge(passreadsum, how = "inner", on="school_name", suffixes = )
passcounter

,Student ID_x,student_name_x,gender_x,grade_x,school_name,reading_score_x,math_score_x,Student ID_y,student_name_y,gender_y,grade_y,reading_score_y,math_score_y
0,0,Paul Bradley,M,9th,Huang High School,66,79,1,Victor Smith,M,12th,94,61
1,0,Paul Bradley,M,9th,Huang High School,66,79,2,Kevin Rodriguez,M,12th,90,60
2,0,Paul Bradley,M,9th,Huang High School,66,79,4,Bonnie Ray,F,9th,97,84
3,0,Paul Bradley,M,9th,Huang High School,66,79,5,Bryan Miranda,M,9th,94,94
4,0,Paul Bradley,M,9th,Huang High School,66,79,6,Sheena Carter,F,11th,82,80
5,0,Paul Bradley,M,9th,Huang High School,66,79,7,Nicole Baker,F,12th,96,69
6,0,Paul Bradley,M,9th,Huang High School,66,79,8,Michael Roth,M,10th,95,87
7,0,Paul Bradley,M,9th,Huang High School,66,79,9,Matthew Greene,M,10th,96,84
8,0,Paul Bradley,M,9th,Huang High School,66,79,10,Andrew Alexander,M,10th,90,70
9,0,Paul Bradley,M,9th,Huang High School,66,79,11,Daniel Cooper,M,10th,78,77
10,0,Paul Bradley,M,9th,Huang High School,66,79,13,William Long,M,9th,71,79
11,0,Paul Bradley,M,9th,Huang High School,66,79,14,Tammy Hebert,F,10th,85,67
12,0,Paul Bradley,M,9th,Huang High School,66,79,15,Dr. Jordan Carson,M,11th,94,88
13,0,Paul Bradley,M,9th,Huang High School,66,79,16,Donald Zamora,M,9th,88,55
14,0,Paul Bradley,M,9th,Huang High School,66,79,17,Kimberly Santiago,F,9th,74,75
15,0,Paul Bradley,M,9th,Huang High School,66,79,19,Brandi Lyons,F,9th,89,80
16,0,Paul Bradley,M,9th,Huang High School,66,79,20,Lisa Davis,F,10th,91,89
17,0,Paul Bradley,M,9th,Huang High School,66,79,21,Kristen Lopez,F,10th,90,77
18,0,Paul Bradley,M,9th,Huang High School,66,79,22,Kimberly Stewart,F,11th,99,84
19,0,Paul Bradley,M,9th,Huang High School,66,79,23,Christopher Parker,M,9th,81,68
20,0,Paul Bradley,M,9th,Huang High School,66,79,24,Chelsea Griffith,F,11th,85,73
21,0,Paul Bradley,M,9th,Huang High School,66,79,25,Cesar Morris,M,9th,92,70
22,0,Paul Bradley,M,9th,Huang High School,66,79,27,Tracey Oconnor,F,10th,80,58
23,0,Paul Bradley,M,9th,Huang High School,66,79,28,Kelly James,F,11th,73,55
24,0,Paul Bradley,M,9th,Huang High School,66,79,29,Nicole Brown,F,12th,90,88
25,0,Paul Bradley,M,9th,Huang High School,66,79,30,Bobby Harris,M,9th,94,99
26,0,Paul Bradley,M,9th,Huang High School,66,79,31,Brian Fernandez,M,10th,97,65
27,0,Paul Bradley,M,9th,Huang High School,66,79,32,Candace Phelps,F,11th,93,90
28,0,Paul Bradley,M,9th,Huang High School,66,79,33,Amy Gonzalez,F,12th,95,68
29,0,Paul Bradley,M,9th,Huang High School,66,79,35,Benjamin Carlson,M,10th,99,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78013504,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39139,Catherine Lee,F,9th,83,81
78013505,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39140,Cheyenne Hernandez,F,9th,76,99
78013506,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39141,Jonathan Sullivan,M,10th,86,93
78013507,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39142,Deborah Higgins DDS,F,10th,96,83
78013508,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39143,Steven Jackson,M,11th,71,93
78013509,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39144,Cristian Webster,M,12th,77,87
78013510,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39145,Audrey Fry,F,10th,94,74
78013511,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39147,Raymond Hawkins,M,10th,88,81
78013512,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39148,Christopher Wilson,M,10th,89,89
78013513,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39149,Glenda Fletcher,F,11th,82,93
78013514,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39150,Jennifer Hamilton,F,11th,80,75
78013515,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39151,Shannon Williams,F,10th,84,73
78013516,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39152,Lori Moore,F,9th,98,84
78013517,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39153,William Hubbard,M,9th,80,75
78013518,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39154,Bradley Johnson,M,12th,91,71
78013519,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39155,John Brooks,M,10th,92,98
78013520,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39156,Stephanie Contreras,F,11th,79,95
78013521,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39157,Kristen Gonzalez,F,9th,79,94
78013522,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39158,Kari Holloway,F,10th,87,90
78013523,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39159,Kimberly Cabrera,F,11th,85,72
78013524,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39160,Katie Weaver,F,11th,89,86
78013525,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39161,April Reyes,F,10th,70,84
78013526,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39162,Derek Weeks,M,12th,94,77
78013527,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39163,John Reese,M,11th,90,75
78013528,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39164,Joseph Anthony,M,9th,97,76
78013529,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39165,Donna Howard,F,12th,99,90
78013530,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39166,Dawn Bell,F,10th,95,70
78013531,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39167,Rebecca Tanner,F,9th,73,84
78013532,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39168,Desiree Kidd,F,10th,99,90
78013533,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,39169,Carolyn Jackson,F,11th,95,75

## Bottom Performing Schools (By Passing Rate)

* Sort and display the five worst-performing schools

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

## Reading Score by Grade

* Perform the same operations as above for reading scores

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [ ]:
# Sample bins. Feel free to create your own bins.
spending_bins = [0, 585, 615, 645, 675]
group_names = ["<$585", "$585-615", "$615-645", "$645-675"]

## Scores by School Size

* Perform the same operations as above, based on school size.

In [ ]:
# Sample bins. Feel free to create your own bins.
size_bins = [0, 1000, 2000, 5000]
group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

## Scores by School Type

* Perform the same operations as above, based on school type.